[project]
name = "boreal"
version = "0.1.0"
readme = "README.md"
description = "TODO"
requires-python = ">=3.11"
dependencies = []

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "yara-python>=4.5.1",
]

[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { file = "Cargo.toml" }, { file = "src/**/*" }]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
